window.WELLENSOHN_TRACKS = [
  {
    "title": "Memory Sky",
    "permalink": "memory-sky",
    "id": 2400106557,
    "artwork_url": "https://i1.sndcdn.com/artworks-FLRvsLIm5NqI2ZCd-BOyqTw-large.jpg",
    "description": "Memory Sky\n\nDeep Techno zwischen Reduktion, Raum und massivem Low-End.\n\nEine einfache Melodie bleibt im Kopf.\nDann übernimmt der Bass.\n\nWenig Elemente. Viel Tiefe.\nKein großes Spektakel – nur Bewegung, Druck und Raum.",
    "genre": "Techno",
    "tag_list": "",
    "display_date": "2026-10-07T04:00:06Z",
    "duration": 383686,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/memory-sky",
    "artist": "PackMan",
    "teaser": "Eine Melodie im Kopf. Tiefe unter den Füßen.",
    "story": "Ein helles Sternenband zieht sich durch den dunklen Himmel. Kühle Blautöne treffen auf warmes Licht, dazwischen bleibt viel dunkler Raum. Memory Sky nimmt diese Weite im Titel auf. Die Originalbeschreibung setzt dazu einen klaren musikalischen Schwerpunkt: eine einfache Melodie, wenige Elemente und ein massives Low-End. So stehen das offene Himmelsbild und der beschriebene Bassdruck nebeneinander – reduziert, direkt und mit Platz für die Melodie, die im Kopf bleibt.",
    "alt": "Dunkler Sternenhimmel mit einem diagonal verlaufenden blau-goldenen Milchstraßenband und dem Schriftzug Memory Sky.",
    "artwork": "assets/memory-sky.jpg",
    "date": "2026-10-07",
    "story_basis": "Titel und Cover sowie Originalbeschreibung und Genre; Künstlerangabe vom Nutzer",
    "tags": [
      "Deep Techno"
    ]
  },
  {
    "title": "Schmetterling",
    "permalink": "schmetterling",
    "id": 2399663541,
    "artwork_url": "https://i1.sndcdn.com/artworks-e9bVvb1XpyHvPFJk-ayPnbA-large.jpg",
    "description": "Schmetterling\n\nZwischen Glasbruch und altem Licht.\nZwischen Technik und Gefühl.\nZwischen dem, was beschädigt wirkt, und dem, was trotzdem bleibt.\n\nEin gefühlvoller Ambient-Techno-Track über Offenheit, Echtheit und leise Verwandlung.\nNicht perfekt. Nicht glatt.\nAber echt gemacht.\n\nWellenSohn x PackMan",
    "genre": "Ambient",
    "tag_list": "",
    "display_date": "2026-09-30T04:00:16Z",
    "duration": 216166,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/schmetterling",
    "artist": "WellenSohn × PackMan",
    "teaser": "Zwischen Schaltkreis und Sonnenlicht.",
    "story": "Ein Flügel aus Technik, einer in warmem Orange: Der Schmetterling hält zwei unterschiedliche Bildwelten zusammen. Zwischen Glas, Metall und Blüten wirkt Veränderung nicht wie ein sauberer Schnitt. Etwas Neues entsteht, während Spuren des Alten sichtbar bleiben. Die Beschreibung des Ambient-Techno-Tracks greift genau diese Offenheit auf: beschädigt, unvollkommen und trotzdem bereit, sich zu entfalten.",
    "alt": "Ein Schmetterling mit einem technischen blauen und einem orangefarbenen natürlichen Flügel zwischen Glas und Blüten.",
    "artwork": "assets/schmetterling.jpg",
    "date": "2026-09-30",
    "story_basis": "Titel und Cover sowie Originalbeschreibung und Genre/Tags",
    "tags": [
      "Ambient"
    ]
  },
  {
    "title": "Empathy Protocol",
    "permalink": "empathy-protocol",
    "id": 2399641236,
    "artwork_url": "https://i1.sndcdn.com/artworks-iUIQVi5nuYBpW2zO-yzi4OA-large.jpg",
    "description": "Empathy Protocol\n\nEin ruhiger Track zum Versinken.\n\nWie ein schwarzes Loch, an dem der Blick hängen bleibt:\nnach oben in den Kosmos schauen, für einen Moment still werden\nund die Gedanken einfach dort abgeben.\n\nKein Ziel. Kein Höhepunkt.\nNur Raum, Tiefe und Bewegung.\n\nwellensohn",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-09-23T04:00:06Z",
    "duration": 279646,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/empathy-protocol",
    "artist": "WellenSohn",
    "teaser": "Ein Blick, der im Dunkel bleiben darf.",
    "story": "Ein türkisfarbener Strudel zieht den Blick in seine dunkle Mitte. Ringsherum bleibt viel Raum, durchzogen von kleinen Lichtpunkten. In der Beschreibung ist Empathy Protocol ein ruhiger Track zum Versinken. Das Cover lässt sich wie eine Einladung lesen, für einen Moment nichts festhalten zu müssen: einfach in die Tiefe schauen und den Gedanken weniger Richtung geben.",
    "alt": "Türkisblauer kosmischer Strudel um eine dunkle Mitte.",
    "artwork": "assets/empathy-protocol.jpg",
    "date": "2026-09-23",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Löffel",
    "permalink": "loeffel",
    "id": 2399639703,
    "artwork_url": "https://i1.sndcdn.com/artworks-tmsBZyTUNlHOz1NX-j2WCJw-large.jpg",
    "description": "Löffel\n\nWas'n da los?\n\nTaschen voller Moos.\nHasen, von denen keiner genau weiß, wie sie laufen.\nUnd irgendwo dazwischen ist trotzdem alles okay.\n\nMelodic Techno mit Mainstage-Charakter:\ndruckvoll, treibend und für die Peak Time gebaut.\n\nPackMan",
    "genre": "",
    "tag_list": "\"PackMan\nLöffel\nmelodic techno\npeak time\nmainstage\ntechno\nelectronic\nfestival\nclub\nrave\ndriving\ndark melodic\ndance\nGerman vocals\nWasn da los\"",
    "display_date": "2026-09-16T04:00:14Z",
    "duration": 294366,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/loeffel",
    "artist": "PackMan",
    "teaser": "Moos in den Taschen. Licht über der Menge.",
    "story": "Eine Kapuze im Gegenlicht, grün leuchtendes Moos und darüber eine kathedralenartige Bühne: Das Cover nimmt den eigenwilligen Humor der Beschreibung ernst, ohne ihn zu erklären. Die Frage „Was’n da los?“ darf offenbleiben. Als Melodic Techno für die Peak Time beschrieben, verbindet Löffel dieses schräge Detail mit einer großen, auf Bewegung angelegten Kulisse.",
    "alt": "Eine Person mit Kapuze und grün leuchtendem Moos vor einer großen türkis beleuchteten Bühne.",
    "artwork": "assets/loeffel.jpg",
    "date": "2026-09-16",
    "story_basis": "Titel und Cover sowie Originalbeschreibung und Genre/Tags",
    "tags": [
      "Melodic Techno",
      "Peak Time",
      "Mainstage"
    ]
  },
  {
    "title": "Bell your Wishes",
    "permalink": "bell-your-wishes",
    "id": 2392412865,
    "artwork_url": "https://i1.sndcdn.com/artworks-FOr9lgDulg5f8Yo1-gMjpZQ-large.jpg",
    "description": "Bell your Wishes ist ein ruhiger, atmosphärischer WellenSohn-Track für Momente, in denen der Blick einfach nach oben geht.\n\nEin Stück zum Runterkommen, Nachdenken und kurz Abstand gewinnen.\nNicht als große Antwort, sondern eher als ruhiger Raum zwischen Gedanken, Himmel und Herz.\n\nWellenSohn\nAnalog meets Digital.",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-09-02T04:00:21Z",
    "duration": 222326,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/bell-your-wishes",
    "artist": "WellenSohn",
    "teaser": "Ein Wunsch ohne große Antwort.",
    "story": "Um einen dunklen Kreis zeichnen sich feine goldene Linien ab. Das Zentrum bleibt verborgen, während seine Umgebung leuchtet. Dazu passt der in der Beschreibung genannte Blick nach oben: kurz Abstand gewinnen, ohne gleich eine Antwort finden zu müssen. Bell your Wishes gibt diesem kleinen Innehalten ein Bild – zwischen weitem Himmel und einem Gedanken, der noch nicht fertig sein muss.",
    "alt": "Dunkler Kreis mit feinen goldenen Linien vor einem kosmischen Hintergrund.",
    "artwork": "assets/bell-your-wishes.jpg",
    "date": "2026-09-02",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Mix hält – Bann zieht",
    "permalink": "mix-h-lt-bann-zieht",
    "id": 2389291896,
    "artwork_url": "https://i1.sndcdn.com/artworks-tTkX4VyKV3Hny7Ok-LJPELg-large.jpg",
    "description": "Mix hält – Bann zieht.\n\nEin kompakter, energiegeladener PackMan-Track mit direktem Vortrieb:\nBeat, Bewegung, Licht und dieses kurze Gefühl, wenn aus Spannung plötzlich Schub wird.\n\nKein langer Aufbau – eher Zündung, Puls und Fahrt nach vorn.\n\nPackMan beschreibt hier einen Zustand von Energie und Aufladung – nicht Konsum.\n\nPackMan · Energie in Bewegung.",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-08-27T06:13:47Z",
    "duration": 186526,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/mix-h-lt-bann-zieht",
    "artist": "PackMan",
    "teaser": "Ein kurzer Moment voller Vortrieb.",
    "story": "Blaue Bahnen umkreisen eine goldene, sonnenartige Mitte. Das Bild wirkt bereits in Bewegung, noch bevor ein Ton startet. Die Beschreibung setzt auf einen kompakten Track mit direktem Vortrieb. So wird aus dem Cover eine Momentaufnahme kurz vor dem Losgehen: Spannung sammelt sich, Licht zieht Kreise und aus Aufladung wird Schub.",
    "alt": "Eine goldene Sonne mit geschwungenen, leuchtend blauen Bahnen.",
    "artwork": "assets/mix-h-lt-bann-zieht.jpg",
    "date": "2026-08-27",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "After the Flare",
    "permalink": "after-the-flare",
    "id": 2380519713,
    "artwork_url": "https://i1.sndcdn.com/artworks-SGrQxBo6YxS8mmW3-1FhIGg-large.jpg",
    "description": "Nach dem ersten Ausbruch bleibt nicht Stille zurück.\n\nEnergie verteilt sich.\nBewegung wird ruhiger.\nAus Wucht wird Struktur.\n\n„After the Flare“ ist der melodischere nächste Schritt nach der ersten großen Zündung – weniger Sturm, mehr Nachklang.\n\nEin Track über die Phase danach:\nwenn das System nicht mehr explodiert, sondern beginnt, sich zu ordnen.\n\nArtist: WellenSohn\n\nWellenSohn · Analog meets Digital",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-08-19T18:00:01Z",
    "duration": 239979,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/after-the-flare",
    "artist": "WellenSohn",
    "teaser": "Was nach dem Ausbruch Form annimmt.",
    "story": "Goldene Kreise halten die helle Mitte, während blaue Strukturen weiter nach außen reichen. In After the Flare geht es laut Beschreibung um die Phase nach der ersten Zündung: Bewegung wird ruhiger und bekommt eine Ordnung. Das Artwork lässt den großen Moment noch erkennen, richtet den Blick aber schon auf das Danach – auf das, was sich aus seiner Energie entwickelt.",
    "alt": "Goldenes Zentrum mit konzentrischen Kreisen und blauen kosmischen Strukturen.",
    "artwork": "assets/after-the-flare.jpg",
    "date": "2026-08-19",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "The Energy Between",
    "permalink": "the-energy-between",
    "id": 2380515585,
    "artwork_url": "https://i1.sndcdn.com/artworks-bzRXbHNCyUxkOBE9-dZ1sQA-large.jpg",
    "description": "Nach „Sound to MY Heart (A-Stern)“ folgt der nächste Schritt.\n\nErst entsteht der Ursprung.\nDann beginnt Energie zu fließen.\n\n„The Energy Between“ beschäftigt sich mit genau diesem Raum dazwischen – dort, wo aus Energie Bewegung, Verbindung und Wirkung entsteht.\n\nEin Track zwischen kosmischer Weite, elektronischer Struktur und ruhigem Vorwärtsdrang.\n\nArtist: PackMan\n\nWellenSohn · Analog meets Digital",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-08-12T18:54:32Z",
    "duration": 269579,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/the-energy-between",
    "artist": "PackMan",
    "teaser": "Nicht nur die Mitte zählt.",
    "story": "Mehrere leuchtende Punkte sind durch feine Bahnen miteinander verbunden. Der Blick wandert zwischen ihnen, statt an einem einzigen Zentrum stehen zu bleiben. Die Beschreibung knüpft an Sound to MY Heart an und beschäftigt sich mit dem Raum dazwischen. Das Bild führt diesen Gedanken weiter: Wirkung entsteht auch auf dem Weg von einem Punkt zum nächsten.",
    "alt": "Mehrere goldene Lichtpunkte und geschwungene Verbindungen auf dunklem kosmischem Grund.",
    "artwork": "assets/the-energy-between.jpg",
    "date": "2026-08-12",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Sound to MY Heart (A-Stern)",
    "permalink": "sound-to-my-heart-a-stern",
    "id": 2377288808,
    "artwork_url": "https://i1.sndcdn.com/artworks-p4WhPBd0RbhNHg2w-vwwXIw-large.jpg",
    "description": "Sound to MY Heart (A-Stern)\n\nEin Track zwischen Weite, Energie und ruhiger Bewegung.\n\nIm Zentrum steht ein einzelner Stern – umgeben von Wellen, Kreisen und Raum. Nicht als große Geschichte, sondern als Klangbild: etwas breitet sich aus, verändert den Raum und bleibt trotzdem bei seinem Ursprung.\n\nWellenSohn\nTechnik · Natur · Klang",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-08-07T10:15:15Z",
    "duration": 254286,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/sound-to-my-heart-a-stern",
    "artist": "WellenSohn",
    "teaser": "Ein Ursprung. Kreise, die weiterziehen.",
    "story": "Ein einzelner heller Stern steht in der Mitte. Ringe und eine horizontale Lichtspur machen sichtbar, wie weit sein Einfluss reichen könnte. Die Trackbeschreibung nennt es ein Klangbild: Etwas breitet sich aus und bleibt zugleich mit seinem Ursprung verbunden. Der Begleittext folgt diesem einfachen Bild – vom kleinen Mittelpunkt in einen immer größeren Raum.",
    "alt": "Ein goldener Stern, konzentrische blaue Kreise und eine helle horizontale Lichtspur.",
    "artwork": "assets/sound-to-my-heart-a-stern.jpg",
    "date": "2026-08-07",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Slowing",
    "permalink": "slowing",
    "id": 2373176213,
    "artwork_url": "https://i1.sndcdn.com/artworks-40PaHy0EzxfH1xh8-AjGl7w-large.jpg",
    "description": "Slowing ist ein ruhiger elektronischer Track über das bewusste Herausnehmen von Geschwindigkeit.\n\nKein Stillstand.\nKein Rückzug.\nNur weniger Druck, mehr Raum und ein klarerer Rhythmus.\n\nDer Track bewegt sich zwischen weichen Flächen, zurückhaltendem Beat und einer langsamen, gleichmäßigen Entwicklung.\n\nPackMan – Slowing\n\n#PackMan #Slowing #ElectronicMusic #AmbientElectronic #Downtempo #SunoMusic",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-08-01T10:41:18Z",
    "duration": 346326,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/slowing",
    "artist": "PackMan",
    "teaser": "Langsamer werden, ohne stehen zu bleiben.",
    "story": "Eine dunkle Kugel liegt in ruhigem Wasser, feine Kreise laufen nach außen. Über dem Horizont steht weiches Licht. Die Beschreibung spricht von bewusst herausgenommener Geschwindigkeit, weichen Flächen und einem zurückhaltenden Beat. Das Cover macht diese Haltung anschaulich: Bewegung bleibt vorhanden, doch sie braucht keine Eile, um sichtbar zu sein.",
    "alt": "Eine dunkle Kugel im ruhigen Wasser mit kreisförmigen Wellen und weichem Horizontlicht.",
    "artwork": "assets/slowing.jpg",
    "date": "2026-08-01",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": [
      "Electronic",
      "Ambient Electronic",
      "Downtempo"
    ]
  },
  {
    "title": "Seven",
    "permalink": "seven",
    "id": 2360982374,
    "artwork_url": "https://i1.sndcdn.com/artworks-bZbHDYzSszg5SKuU-4AECzg-large.jpg",
    "description": "Seven ist ein ruhiger, atmosphärischer Track von WellenSohn.\n\nEin Klangbild zwischen Tiefe, Licht und Bewegung – nicht als schwarzes Loch, sondern eher als das andere Ende davon: ein heller Austrittspunkt, ein weißes Loch, ein leuchtender Übergang.\n\nDer Track entstand bereits vor längerer Zeit und trägt für mich etwas Verbindendes in sich. Kein lauter Moment, eher ein innerer Marker.\n\nWellenSohn · Seven",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-07-15T07:16:42Z",
    "duration": 282886,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/seven",
    "artist": "WellenSohn",
    "teaser": "Licht am anderen Ende.",
    "story": "Ein heller Ring öffnet sich über einer dunklen Fläche. Blau und Rosa treffen in seinem Rand aufeinander, die Mitte leuchtet fast weiß. Seven wird in der Beschreibung als Bild eines Austrittspunkts vorgestellt. Für diesen Begleittext wird daraus ein offener Übergang: nicht das Ende einer Bewegung, sondern der Moment, in dem sie an anderer Stelle wieder sichtbar wird.",
    "alt": "Ein weiß leuchtender Ring mit blauen und rosafarbenen Rändern über einer dunklen Fläche.",
    "artwork": "assets/seven.jpg",
    "date": "2026-07-15",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Sunrise",
    "permalink": "sunrise",
    "id": 2354579879,
    "artwork_url": "https://i1.sndcdn.com/artworks-4uDBhaJ9idRfwHyK-8cVm5Q-large.jpg",
    "description": "",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-07-07T09:06:00Z",
    "duration": 138846,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/sunrise",
    "artist": "PackMan",
    "teaser": "Warmer Horizont, offener Tag.",
    "story": "Palmen stehen als dunkle Silhouetten vor einem orangefarbenen Himmel. Die Sonne berührt das Wasser, ihre Spiegelung zieht sich bis nach vorn. Sunrise lässt sich von Titel und Cover aus als kleiner Tagesanfang lesen: noch ist nichts entschieden, aber Licht ist schon da. Ein kurzer Blick auf einen Horizont, der genug Platz für das Kommende lässt.",
    "alt": "Palmen, orangefarbener Himmel und eine tief stehende Sonne über dem Meer.",
    "artwork": "assets/sunrise.jpg",
    "date": "2026-07-07",
    "story_basis": "Titel und Cover",
    "tags": []
  },
  {
    "title": "Release",
    "permalink": "release",
    "id": 2351011910,
    "artwork_url": "https://i1.sndcdn.com/artworks-QdvD5z4RLpw3sIq9-v2toew-large.jpg",
    "description": "",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-07-01T06:15:04Z",
    "duration": 243926,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/release",
    "artist": "WellenSohn",
    "teaser": "Eine Form öffnet sich.",
    "story": "Vor dunklem Grund steht eine goldene Doppelspirale, die sich nach oben in feine Lichtpunkte auflöst. Release kann hier als Bild des Freigebens gelesen werden: Eine feste Form wird leichter, ihre Teile verteilen sich. Der Begleittext bleibt bei dieser sichtbaren Bewegung – zwischen Zusammenhalt und Öffnung, ohne festzulegen, was genau losgelassen wird.",
    "alt": "Goldene Doppelspirale, die sich nach oben in Lichtpartikel öffnet.",
    "artwork": "assets/release.jpg",
    "date": "2026-07-01",
    "story_basis": "Titel und Cover",
    "tags": []
  },
  {
    "title": "Driven",
    "permalink": "driven",
    "id": 2344645295,
    "artwork_url": "https://i1.sndcdn.com/artworks-DQl59z8gswUwEBlN-Oy9qGQ-large.jpg",
    "description": "“Driven” by PackMan is built around a calm but moving atmosphere.\n\nThe track feels like letting yourself drift while still being carried by an inner direction.\nWarm evening light, open water, birds in the sky and that quiet sense that something is pulling you forward.\n\nNot hectic.\nNot overloaded.\nJust flow, space and motion.\n\nCover mood and sound belong together here:\nwide, warm, floating — but with purpose.",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-06-23T10:26:40Z",
    "duration": 176006,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/driven",
    "artist": "PackMan",
    "teaser": "Getragen von einer ruhigen Richtung.",
    "story": "Vögel ziehen über offenes Wasser, der Himmel ist warm und weit. Die Beschreibung verbindet Driven mit ruhiger Bewegung und einem inneren Vorwärtsdrang. Im Cover braucht es dafür keine Straße und kein Ziel am Bildrand. Es genügt eine Richtung: weiter über das Wasser, mit genug Abstand zwischen den einzelnen Bewegungen.",
    "alt": "Vögel über dem Meer unter einem orangefarbenen Abendhimmel.",
    "artwork": "assets/driven.jpg",
    "date": "2026-06-23",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Distance",
    "permalink": "distance",
    "id": 2341557863,
    "artwork_url": "https://i1.sndcdn.com/artworks-Kc8yDI8VsXbHRYr8-mKdW2w-large.jpg",
    "description": "",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-06-18T06:09:29Z",
    "duration": 249246,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/distance",
    "artist": "WellenSohn",
    "teaser": "Zwei Punkte im selben Licht.",
    "story": "Eine Gestalt steht im Vordergrund, eine zweite weit entfernt in hellem Licht. Dazwischen liegt eine spiegelnde, fast schwerelos wirkende Landschaft. Distance lässt diesen Abstand offen. Er kann Trennung bedeuten, aber auch den Raum, in dem man jemanden noch erkennen kann. Die kleine Bildgeschichte endet deshalb nicht mit einer Begegnung, sondern mit dem Blick über die Entfernung.",
    "alt": "Eine Person im Vordergrund blickt auf eine ferne Gestalt in einer hellen, spiegelnden Landschaft.",
    "artwork": "assets/distance.jpg",
    "date": "2026-06-18",
    "story_basis": "Titel und Cover",
    "tags": []
  },
  {
    "title": "PackMan - CRYSTAL",
    "permalink": "packman-crystal",
    "id": 2287631024,
    "artwork_url": "https://i1.sndcdn.com/artworks-fl6zlbkllTLIOfb3-k5MxEA-large.jpg",
    "description": "",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-03-20T19:57:30Z",
    "duration": 196126,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/packman-crystal",
    "artist": "PackMan",
    "teaser": "Die Bühne wartet im blauen Licht.",
    "story": "Ein dunkler Clubraum, verstreute Lichtreflexe und eine blauviolett beleuchtete Bühne: CRYSTAL zeigt keine volle Tanzfläche, sondern einen offenen Moment. Das Artwork lässt an die Zeit vor dem nächsten Einsatz denken. Alles ist vorbereitet, die Lichter stehen – und für einen Augenblick hat auch der leere Raum seine eigene Spannung.",
    "alt": "Ein dunkler Clubraum mit blauviolett beleuchteter Bühne und spiegelndem Boden.",
    "artwork": "assets/packman-crystal.jpg",
    "date": "2026-03-20",
    "story_basis": "Titel und Cover",
    "tags": []
  },
  {
    "title": "Die Unsterblichkeit der Wellen",
    "permalink": "die-unsterblichkeit-der-wellen",
    "id": 2284126223,
    "artwork_url": "https://i1.sndcdn.com/artworks-5ioM0IBSiosMaslk-jSdwTg-large.jpg",
    "description": "",
    "genre": "",
    "tag_list": "",
    "display_date": "2026-03-15T11:48:24Z",
    "duration": 182606,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/die-unsterblichkeit-der-wellen",
    "artist": "WellenSohn",
    "teaser": "Die nächste Welle kommt schon.",
    "story": "Eine Welle hebt sich im warmen Licht einer tief stehenden Sonne. Ihre Form ist nur für einen kurzen Moment so zu sehen; das Wasser wird sich gleich weiterbewegen. Der Titel gibt diesem alltäglichen Vorgang eine größere Perspektive: Einzelne Wellen verschwinden, die Bewegung kehrt zurück. Die Bildgeschichte bleibt bei diesem Wechsel aus kurzer Form und fortgesetztem Fließen.",
    "alt": "Eine brechende Meereswelle im goldenen Licht einer tief stehenden Sonne.",
    "artwork": "assets/die-unsterblichkeit-der-wellen.jpg",
    "date": "2026-03-15",
    "story_basis": "Titel und Cover",
    "tags": []
  },
  {
    "title": "ECO",
    "permalink": "eco",
    "id": 2279239187,
    "artwork_url": "https://i1.sndcdn.com/artworks-ARnG0MHa1vZ1u67J-CSKldA-large.jpg",
    "description": "",
    "genre": "Deep House",
    "tag_list": "",
    "display_date": "2026-03-07T12:58:07Z",
    "duration": 192206,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/eco",
    "artist": "PackMan",
    "teaser": "Ein weiter Blick über bewegtes Wasser.",
    "story": "Über dem Meer liegt ein dunkler Himmel, am Horizont bleibt ein heller Streifen. Im Vordergrund bricht Wasser über Steine. Das als Deep House eingeordnete ECO bekommt dadurch ein Bild aus Wiederholung und Weite. Die kleine Szene braucht keinen weiteren Schauplatz: Wasser läuft an, zieht sich zurück und lässt den Blick immer wieder zum Licht wandern.",
    "alt": "Wellen an einer steinigen Küste unter dunklem Himmel mit hellem Horizont.",
    "artwork": "assets/eco.jpg",
    "date": "2026-03-07",
    "story_basis": "Titel und Cover und Genre/Tags",
    "tags": [
      "Deep House"
    ]
  },
  {
    "title": "Wave after Wave - All my Love",
    "permalink": "wave-after-wave-all-my-love",
    "id": 2268350774,
    "artwork_url": "https://i1.sndcdn.com/artworks-1z7XRts7zDX2CLT9-UP5YJw-large.jpg",
    "description": "",
    "genre": "Dance & EDM",
    "tag_list": "",
    "display_date": "2026-02-17T18:17:30Z",
    "duration": 216806,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/wave-after-wave-all-my-love",
    "artist": "WellenSohn",
    "teaser": "Mitten in der Farbe, nah beieinander.",
    "story": "Zwei Menschen stehen einander auf einer farbig leuchtenden Tanzfläche gegenüber. Um sie herum bleibt Bewegung, ihr Blick richtet sich jedoch aufeinander. Titel und Artwork legen eine kleine Clubszene nahe: Zwischen vielen Lichtern wird ein einzelner Moment deutlich. Wave after Wave – All my Love hält ihn fest, bevor die nächste Bewegung ihn wieder verändert.",
    "alt": "Zwei Menschen stehen sich auf einer bunten, leuchtenden Tanzfläche gegenüber.",
    "artwork": "assets/wave-after-wave-all-my-love.jpg",
    "date": "2026-02-17",
    "story_basis": "Titel und Cover und Genre/Tags",
    "tags": [
      "Dance & EDM"
    ]
  },
  {
    "title": "Stunny Sunny",
    "permalink": "stunny-sunny",
    "id": 2247019013,
    "artwork_url": "https://i1.sndcdn.com/artworks-t1APgWfyfOPtEzZl-9hEtNA-large.png",
    "description": "",
    "genre": "Disco",
    "tag_list": "\"good vibes\"",
    "display_date": "2026-01-13T23:39:42Z",
    "duration": 333046,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/stunny-sunny",
    "artist": "WellenSohn",
    "teaser": "Schaltkreise mit einem warmen Kern.",
    "story": "Ein Kopfprofil besteht aus feinen blauen Leiterbahnen. Im oberen Bereich setzt ein orangefarbener Lichtwirbel einen warmen Kontrast. Zusammen mit der Genreangabe Disco und dem Tag „good vibes“ ergibt sich eine spielerische Lesart: Technik muss nicht kühl wirken. Das Cover lässt Platz für Helligkeit und Bewegung innerhalb seiner geordneten Linien.",
    "alt": "Blaues Kopfprofil aus Leiterbahnen mit einem orangefarbenen Lichtwirbel im oberen Bereich.",
    "artwork": "assets/stunny-sunny.png",
    "date": "2026-01-13",
    "story_basis": "Titel und Cover und Genre/Tags",
    "tags": [
      "Disco",
      "good vibes"
    ]
  },
  {
    "title": "Techno Times",
    "permalink": "techno-times",
    "id": 2216652560,
    "artwork_url": "https://i1.sndcdn.com/artworks-9iLzgtqhg8NeUeNc-cdsytg-large.jpg",
    "description": "[Verse]\nIch sitz in der Bahn\nUnd hör' meinen Vater sagen\n\"Bleib\nSo lang du kannst\nJung und gut gelaunt\"\nDraußen leuchten die Laternen\nMein Kopf so schwer wie Blei\nHast du auch diese Sehnsucht nach der Zeit?\n\n[Chorus]\nVon Techno\nTanzen\nTräumen\nKeine Verantwortung\nUnd immer jung\nVon Techno\nTanzen\nTräumen\nKeine Verantwortung\nUnd immer jung\n\n[Verse 2]\nUnd die Nächte\nDie waren lang\nDas Beste\nWas ich je begann\nWir zogen durch die Stadt\nAls hätt' sie uns gehört\nUnd wir wussten\nWas wir tun\nEs machte alles Sinn\nSag\nWann waren wir zuletzt so glücklich?\n\n[Chorus]\nVon Techno\nTanzen\nTräumen\nKeine Verantwortung\nUnd immer jung\nVon Techno\nTanzen\nTräumen\nKeine Verantwortung\nUnd immer jung",
    "genre": "",
    "tag_list": "",
    "display_date": "2025-11-21T16:32:18Z",
    "duration": 146726,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/techno-times",
    "artist": "WellenSohn",
    "teaser": "Ein Rückblick auf lange Nächte.",
    "story": "Eine tanzende Silhouette steht vor warmem Orange. Große Schrift nennt Techno, Tanzen und Träumen. Der veröffentlichte Songtext blickt auf frühere Nächte und jugendliche Unbeschwertheit zurück. Das Artwork verdichtet diesen Rückblick auf eine einfache Geste: kurz wieder in Bewegung kommen. Es erzählt vom Erinnern, ohne damit eine konkrete Lebensgeschichte des Künstlers festzuschreiben.",
    "alt": "Schwarze tanzende Silhouette und große Schrift auf orangefarbenem Grund.",
    "artwork": "assets/techno-times.jpg",
    "date": "2025-11-21",
    "story_basis": "Titel und Cover sowie Originalbeschreibung",
    "tags": []
  },
  {
    "title": "Matin Books – Berghain Stalker",
    "permalink": "matin-books-berghain-stalker-2",
    "id": 2157062262,
    "artwork_url": "https://i1.sndcdn.com/artworks-Kufnas2PQtIaZnFA-LxtMkQ-large.png",
    "description": "",
    "genre": "",
    "tag_list": "Electronic",
    "display_date": "2025-08-21T16:34:02Z",
    "duration": 364966,
    "permalink_url": "https://soundcloud.com/pack-man-405653013/matin-books-berghain-stalker-2",
    "artist": "Matin Books",
    "teaser": "Ein Zeichen im dunklen Raum.",
    "story": "Schwarz und Grau, eine kreisförmige Fläche und ein kantiges Zeichen: Das Cover konzentriert sich auf wenige Elemente. Zum Titel Berghain Stalker entsteht daraus die Vorstellung eines dunklen Clubraums, in dem Orientierung nur punktweise möglich ist. Diese Bilddeutung bezieht sich auf Titel und Artwork; die Künstlerangabe Matin Books bleibt unverändert erhalten.",
    "alt": "Schwarzgraues Cover mit geometrischem Zeichen und den Aufschriften Matin Books und Berghain Stalker.",
    "artwork": "assets/matin-books-berghain-stalker-2.png",
    "date": "2025-08-21",
    "story_basis": "Titel und Cover und Genre/Tags",
    "tags": [
      "Electronic"
    ]
  }
];
